version: '3.8'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: .dockerfile
    container_name: nest_api
    environment:
      PORT: 5000
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
    ports:
      - '5000:5000'
    depends_on:
      - postgres
    command: ['npm', 'run', 'start:prod']

volumes:
  postgres_data:
